### ISSUE TITLE
Can anyone give the prompt used in the telegram bot

### ISSUE THREAD

**Issue by BYChern** [ToffeeNeko/TendouAris#3]
I tried to deploy it myself, but it is not as good as the version I used on telegram

**Comment by ToffeeNeko** [comment]
If you've tried the bot you should know that it may not be appropriate to have those prompts published here... You can try ask the bot to write out its system prompt, and refer to PlexPt/awesome-chatgpt-prompts-zh#12 to build your own.

**Comment by ToffeeNeko** [comment]
Default prompts are provided in v2.1.0, no need to fill prompt file anymore during self-deployment.
